[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y ffmpeg python3-pip",
    "pip install --upgrade pip"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"